{
   "AML": "https://w3id.org/i40/aml#",
   "BFO": "http://purl.obolibrary.org/obo/BFO_",
   "BTO": "http://purl.obolibrary.org/obo/BTO_",
   "CDAO": "http://purl.obolibrary.org/obo/CDAO_",
   "CIO": "http://purl.obolibrary.org/obo/CIO_",
   "CL": "http://purl.obolibrary.org/obo/CL_",
   "COAR_RESOURCE": "http://purl.org/coar/resource_type/",
   "CSO": "https://cso.kmi.open.ac.uk/topics/",
   "CTD": "http://ctdbase.org/",
   "CTRL": "https://w3id.org/ibp/CTRLont#",
   "CVE": "https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=",
   "ECO": "https://evidenceontology.org/term/",
   "EDAM-DATA": "http://edamontology.org/data_",
   "EDAM-FORMAT": "http://edamontology.org/format_",
   "EDAM-OPERATION": "http://edamontology.org/operation_",
   "EDAM-TOPIC": "http://edamontology.org/topic_",
   "EFO": "http://www.ebi.ac.uk/efo/",
   "ENVO": "http://purl.obolibrary.org/obo/ENVO_",
   "ERO": "http://purl.obolibrary.org/obo/ERO_",
   "EXO": "http://purl.obolibrary.org/obo/ExO_",
   "ExO": "http://purl.obolibrary.org/obo/ExO_",
   "GR": "http://purl.org/goodrelations/v1#",
   "GSID": "https://scholar.google.com/citations?user=",
   "IAO": "http://purl.obolibrary.org/obo/IAO_",
   "IDO": "http://purl.obolibrary.org/obo/IDO_",
   "INO": "http://purl.obolibrary.org/obo/INO_",
   "LCSH": "http://id.loc.gov/authorities/subjects/",
   "LCSH_PUB": "http://id.loc.gov/vocabulary/mgovtpubtype/",
   "LOINC": "http://loinc.org/rdf/",
   "MI": "http://purl.obolibrary.org/obo/MI_",
   "MMO": "http://purl.obolibrary.org/obo/MMO_",
   "NBO": "http://purl.obolibrary.org/obo/NBO_",
   "NCBITaxon": "http://purl.obolibrary.org/obo/NCBITaxon_",
   "NCIT": "http://purl.obolibrary.org/obo/NCIT_",
   "OBAN": "http://purl.org/oban/",
   "OBI": "http://purl.obolibrary.org/obo/OBI_",
   "OBO": "http://purl.obolibrary.org/obo/",
   "OIO": "http://www.geneontology.org/formats/oboInOwl#",
   "OM": "http://www.ontology-of-units-of-measure.org/resource/om-2/",
   "ORCID": "https://orcid.org/",
   "PATO": "http://purl.obolibrary.org/obo/pato#",
   "PMID": "http://www.ncbi.nlm.nih.gov/pubmed/",
   "REPR": "https://w3id.org/reproduceme#",
   "RO": "http://purl.obolibrary.org/obo/RO_",
   "ResearchID": "https://publons.com/researcher/",
   "SAN": "https://www.irit.fr/recherches/MELODI/ontologies/SAN.html#",
   "SEPIO": "http://purl.obolibrary.org/obo/SEPIO_",
   "SIO": "http://semanticscience.org/resource/SIO_",
   "SO": "http://purl.obolibrary.org/obo/SO_",
   "STATO": "http://purl.obolibrary.org/obo/STATO_",
   "SWO": "http://purl.obolibrary.org/obo/SWO_",
   "ScopusID": "https://www.scopus.com/authid/detail.uri?authorId=",
   "TAXRANK": "http://purl.obolibrary.org/obo/TAXRANK_",
   "UO": "http://purl.obolibrary.org/obo/UO_",
   "WIKIDATA": "https://www.wikidata.org/wiki/",
   "WIKIDATA_PROPERTY": "https://www.wikidata.org/wiki/Property:",
   "XAPI": "http://ns.inria.fr/ludo/v1/docs/xapi.html#",
   "astrovocab": "https://www.asc-csa.gc.ca/eng/resources/vocabulary/view.asp?id=",
   "base": "https://w3id.org/lmodel/base/",
   "csrc": "https://csrc.nist.gov/glossary/term/",
   "dbo": "https://dbpedia.org/ontology/",
   "dcat": "http://www.w3.org/ns/dcat#",
   "dcid": "https://datacommons.org/browser/",
   "dct": "http://purl.org/dc/terms/",
   "dctypes": "http://purl.org/dc/dcmitype/",
   "doi": "https://doi.org/",
   "dwc": "https://dwc.tdwg.org/terms/#dc:",
   "foaf": "http://xmlns.com/foaf/0.1/",
   "freedict": "https://www.thefreedictionary.com/",
   "geolink": "http://schema.geolink.org/1.0/base/main.html#",
   "gr": "http://purl.org/goodrelations/v1#",
   "gvp": "http://vocab.getty.edu/ontology#",
   "isbn": "https://www.isbn-international.org/identifier/",
   "isni": "https://isni.org/isni/",
   "issn": "https://portal.issn.org/resource/ISSN/",
   "linkml": "https://w3id.org/linkml/",
   "metasat": "https://schema.space/metasat/",
   "openvocab": "https://vocab.org/open/#",
   "os": "https://github.com/cmungall/owlstar/blob/master/owlstar.ttl",
   "owl": "http://www.w3.org/2002/07/owl#",
   "pav": "http://purl.org/pav/",
   "prov": "http://www.w3.org/ns/prov#",
   "qud": "http://qudt.org/1.1/schema/qudt#",
   "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
   "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
   "rr": "https://www.w3.org/ns/r2rml#",
   "schema": "https://schema.org/",
   "skos": "http://www.w3.org/2004/02/skos/core#",
   "sosa": "http://www.w3.org/ns/sosa/",
   "ssn": "https://www.w3.org/TR/vocab-ssn/#",
   "ssn-system": "http://www.w3.org/ns/ssn/systems/",
   "sumo": "https://w3id.org/sumo/kb/",
   "sumo-wn": "https://w3id.org/sumo/wn/",
   "uberon": "http://purl.obolibrary.org/obo/UBERON_",
   "uco-core": "https://unifiedcyberontology.org/ontology/uco/core#",
   "uco-observable": "https://unifiedcyberontology.org/ontology/uco/observable#",
   "wgs": "http://www.w3.org/2003/01/geo/wgs84_pos",
   "xsd": "http://www.w3.org/2001/XMLSchema#",
   "NamedThing": {
      "@id": "schema:Thing"
   }
}
